name: AWS RDS available engine versions
description: List AWS RDS available engine versions and update the version file and push tags
inputs:
  version_file:
    description: file path where versions are written
    required: false
    default: versions.txt
  github_token:
    description: GitHub Access Token
    required: true
runs:
  using: composite
  steps:
    - run: bash "${{ github.action_path }}/update.sh"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        VERSION_FILE: ${{ inputs.version_file }}
